[*] --> idle
idle -[dashed]-> go_straight_idle
go_straight_idle: green led
go_straight_idle --> go_straight_inlet: inlet is trigered
go_straight_inlet: red led
go_straight_inlet --> pass_straight_ended: outlet_straight is trigered
pass_straight_ended: blue led

idle -[dashed]-> turn_right_idle
turn_right_idle: green led
turn_right_idle -->turn_right_inlet : inlet is trigered
turn_right_inlet: red led
turn_right_inlet --> turn_right_ended: outlt_turn_right is trigered
turn_right_ended: blue led

