@startuml

frame lua_engin{
    card lua_dostring

}
    collections lua_driver
    card board
    lua_dostring --> lua_driver
    lua_driver --> board


frame robot{
    frame cnc{
        queue gcode_queue
        frame arm_solution{
            card IK
            card FK
            card MiddleKinematic
            IK <-[dashed]- MiddleKinematic
        }
        frame planner{ 
        }
        queue move_blocks

        planner <-- gcode_queue 
        planner <-[dashed]- IK
        planner --> move_blocks


    }
    frame mover{
        collections actuators
    }
    move_blocks --> actuators
}


frame AppBase{
    frame text_message_dispatch{
        card dispatcher
    }
    queue text_message_queue
    card feedback
    card mqtt_client

    text_message_queue <-- mqtt_client
    feedback --> mqtt_client:  publish feedback
    text_message_queue -[dashed]>feedback: check free buffer size

    frame file_system{
        card line_reader
        card file_reader
        line_reader <-[dashed]- file_reader
    }
}

dispatcher <-- text_message_queue
gcode_queue <-- dispatcher 
lua_dostring <-- dispatcher 

card app_logic_on_lua_script_file
lua_dostring  <-- line_reader: lua script line
app_logic_on_lua_script_file <-[#red,dashed]- lua_engin


@enduml