@startuml
card 一排三个_共三排
frame 三角瓶{
    card 样品
}

card 滴定液
frame 二维线性模组{
    card 颜色传感器
}
card 流量计

card 滴定泵
card 滴定管
card 磁力搅拌器
滴定液 --> 滴定泵
滴定泵 --> 流量计: 计算流量
流量计 --> 滴定管
滴定管 --> 三角瓶 

样品 --> 颜色传感器


card 控制器
card PC机

控制器 <--> PC机
控制器 -[#red]-> 磁力搅拌器: 1__启动搅拌器 6A__关闭搅拌器
控制器 -[#red]-> 二维线性模组: 2__移动到目标位置
控制器 -[#red]-> 滴定泵: 3__开启滴定泵， 6B__关闭滴定泵
颜色传感器 -[#green]-> 控制器: 4__颜色判定变色
流量计 -[#green]-> 控制器: 5__读流量


@enduml