@startuml
allowmixing

card app
frame Remote_binary_output_group{
    card remote_binary_output_group
    card MqttSubscriberBase
    remote_binary_output_group <-[dashed]- MqttSubscriberBase
}
card ws2812B


app <-- remote_binary_output_group


app --> ws2812B

MqttSubscriberBase <-- MqttClient


@enduml