	
@startuml

node WMS
node WCS
database database
node webserver
node browser
agent robot_row_0
agent robot_row_1
node shipout_box_in
node deposite_queue
actor operator_1
actor operator_2
node pick_place_button

WMS == webserver
webserver ~~ browser
browser == operator_1

WMS <==> database : deposit \n withdraw_order \n 
WCS <==> database : withdraw_queue
WCS --> robot_row_0 : move_to
WCS --> robot_row_1 : move_to
WCS --> robot_row_2 : move_to
WCS --> robot_row_3 : move_to
WCS --> packer: move_to
robot_shipper --> WCS: shipped_button
robot_packer --> WCS: packed_button
WCS --> shipper: move_to

WMS -->deposite_queue: box_id \n(via mqtt)
deposite_queue --> WCS: box_id\n (from button, \nvia mqtt)

robot_row_0 --> operator_2:  picking
operator_2 --> shipout_box_in: place

pick_place_button --> WCS

@enduml