	
@startuml

node WMS
node WCS
database database
node webserver
node browser
node shipout_box_out
actor operator_1

WMS == webserver
webserver ~~ browser
browser == operator_1

WMS <==> database : deposit \n withdraw_order \n 

WMS -->shipout_box_out: box_id \n(via mqtt)
shipout_box_out --> WCS: box_id\n (from button, \nvia mqtt)

pick_place_button --> WCS

@enduml