@startuml
[*] -> idle

idle-[#red,bold]-> checking_deposit_mq
checking_deposit_mq -[#red,bold]-> deposit: deposit(row, col, quantity) \nrobot[row].moveto(col)
deposit -[#red,bold]-> idle: user_finished, \nuser_canceled

checking_deposit_mq --> checking_withdraw_mq: mq is empty
checking_withdraw_mq --> idle: mq is empty
checking_withdraw_mq --> withdraw: withdraw(list(row,col))
withdraw -> idle: withdraw_list is empty


  state robot_row {
    [*] -> row_idle 
    row_idle -> moving
    moving -> ready
  }
  
state robot_layer{
  [*] -> layer_idle
  layer_idle -[#green,bold]-> picking
  picking -[#green,bold]-> ir_checking: .     .
  ir_checking -[#green,bold]-> drop: ir is blocked
  drop -[#green,bold]-> dropped
  ir_checking -[#green,bold]-> drop: ir is empty >=3 \nLog this fail
  ir_checking -[#green,bold]-> picking: ir is empty <3

  ' dropped -[#green]-> layer_idle




  ready -[#green,bold,dashed]->layer_idle: the ready row_id
  ' dropped -[#green]-> row_idle

}
withdraw -[#green,bold,dashed]-> layer_idle
layer_idle -[#green,bold,dashed]-> row_idle

dropped -[#green,bold,dashed]-> withdraw


' drop_folk -[#green,bold]-> withdraw: remove one item in list.




@enduml
