@startuml


state to_idle   <<fork>>
' state send_G1   <<fork>>


[*] -> idle
idle --> moving 
' send_G1 --> moving
' moving --> ready: M408
ready --> picking_place:  turn on green led
picking_place --> to_idle:  green_button_pressed
to_idle --> idle


state robot_porter {
  [*] -> porter_idle 
  porter_idle --> porter_moving
  porter_moving -> porter_ready
}
moving --> porter_moving: send G1
' to_idle --> row_idle
porter_ready --> ready
to_idle --> porter_idle

@enduml
