print("****************************************************")
print("*                                                  *")
print("*                                                  *")
print("*                                                  *")
print("*                                                  *")
print("*                                                  *")
print("*             RUNNING    LUA                       *")
print("*             RUNNING    mmm                     *")
print("*                                                  *")
print("*                                                  *")
print("*                                                  *")

print("*                                                  *")
print("*                                                  *")
print("*                                                  *")
print("*                                                  *")
print("*                                                  *")
print("****************************************************")
