@startuml
allowmixing

folder Warehouse{
    collections Order
    collections Order_Item
    Order -> Order_Item
}

folder Workers{
    collections loop_porter
    collections Deck
    collections picker_placer

}
Order --> Deck
Order_Item --> loop_porter
Order_Item -->picker_placer

folder Components{
    collections indicator
    collections button
    collections valve


}
Workers --> indicator
Workers --> valve
Workers <-- button


folder Communicators{
    collections gcode_sender
    collections remote_var
}
loop_porter ---> gcode_sender
picker_placer ---> gcode_sender
indicator --> remote_var
valve --> remote_var
button <-- remote_var

@enduml