@startuml
allowmixing

folder Warehouse{
    collections Order
    collections Order_Item
    Order -> Order_Item
}

folder Workers{
    component loop_porter
    component Deck
    component picker_placer

}
Order --> Deck
Order_Item --> loop_porter
Order_Item -->picker_placer

folder SimleWorkers{
    collections indicator
    collections button

}
loop_porter --> indicator
Deck --> indicator
Deck <-- button


folder Communications{
    component gcode_sender
    component remote_var
}
loop_porter ---> gcode_sender
picker_placer ---> gcode_sender
indicator --> remote_var
button <-- remote_var

@enduml