@startuml 订单流程
[*] -> 收到牙模
收到牙模 -> 录入排牙牙位
录入排牙牙位 -> 加工中
加工中 -> 试戴已发货
试戴已发货 --> 返工
返工 -> 返工生产中
试戴已发货 -> 已出货
已出货 --> 已删除

state 加工进度{
[*] -> 上颌架 
上颌架 -> 排牙
排牙 -> 注胶
注胶 -> 抛光
抛光 --> 质检部
质检部 -->完成
}



@enduml