@startuml
allowmixing

frame NodeRed
card Browser_a
card Browser_b
NodeRed ---> Browser_a : http
NodeRed --> Browser_b : http
    actor Trump_finger
    actor Trump_eye
    Browser_a --> Trump_eye : Final user UI

actor You_are_here
    

Browser_b --> You_are_here : debug UI

frame MQTT_broker
MQTT_broker -> NodeRed


frame Human_body{
    frame Esp32{
        frame Node{
            card Nodes_state
            card Sensors_state

            frame Sensor{
                queue Untouched_SensorValue_history
                card Sensor_value
                card Sensor_State
                Untouched_SensorValue_history <-- Sensor_value
                Sensor_State <-- Untouched_SensorValue_history
                Sensor_State -[dashed]-> Untouched_SensorValue_history
            }
            Sensors_state <-- Sensor_State
        }
        card MqttAgent
        MqttAgent <-- Nodes_state
        MqttAgent <-- Sensors_state

    }
    MQTT_broker <-- MqttAgent
    card  I2C____________I2C_BUS________________BUS

    collections Mega328
    collections CapSensor
    Nodes_state <-[#red,dashed]---- I2C____________I2C_BUS________________BUS
    I2C____________I2C_BUS________________BUS <-[#red,dashed]- Mega328
    Sensor_value <-- Mega328
    Mega328 <-- CapSensor
    card GPIO_PIN
    CapSensor <-- GPIO_PIN
}
card Niddle
GPIO_PIN <-- Niddle
Niddle <- Trump_finger

@enduml